**1. Basic**

In [4]:
input =  [1.5, 3.5, 8.9, 10.5, 7.8]
weights = [0.5, 1.5, 0.9, 0.5, 0.8]
bias = 3

output = input[0] * weights[0] + input[1] * weights[1] + input[2] * weights[2] + input[3] * weights[3] + input[4] * weights[4] + bias

print(output)

28.5


In [5]:
input =  [1.5, 3.5, 8.9, 10.5, 7.8]
weights1 = [0.5, 1.5, 0.9, 0.5, 0.8]
weights2 = [1.5, 1.5, 1.9, 4.5, 0.8]
weights3 = [0.25, -1.5, -0.9, 0.5, 7.8]
bias1 = 3
bias2 = 2
bias3 = 1
output = [input[0] * weights1[0] + input[1] * weights1[1] + input[2] * weights1[2] + input[3] * weights1[3] + input[4] * weights1[4] + bias1,
          input[0] * weights2[0] + input[1] * weights2[1] + input[2] * weights2[2] + input[3] * weights2[3] + input[4] * weights2[4] + bias2,
          input[0] * weights3[0] + input[1] * weights3[1] + input[2] * weights3[2] + input[3] * weights3[3] + input[4] * weights3[4] + bias3]

print(output)

[28.5, 79.89999999999999, 54.205]


In [6]:
input =  [1.5, 3.5, 8.9, 10.5, 7.8]
          
weight = [[0.5, 1.5, 0.9, 0.5, 0.8],
          [1.5, 1.5, 1.9, 4.5, 0.8],
          [0.25, -1.5, -0.9, 0.5, 7.8]]

bias = [3, 2, 1]

layer_output = []
for neuron_weight, neuron_bias in zip(weight, bias):
    neuron_output = 0
    for n_input, weight in zip(input, neuron_weight):
        neuron_output += n_input*weight
    neuron_output += neuron_bias
    layer_output.append(neuron_output)
print(layer_output)

[28.5, 79.89999999999999, 54.205]


**2. Produto Escalar**

In [8]:
import numpy as np 
input =  [1.5, 3.5, 8.9, 10.5, 7.8]
weight = [0.5, 1.5, 0.9, 0.5, 0.8]
output = np.dot(input, weight)
print(output)

25.499999999999996


In [9]:
input =  [[1.5, 3.5, 8.9, 10.5, -0.8],
         [2.5, 4.5, 8.9, 0.5, -7.8],
         [3.5, 3.5, 6.9, 0.5, 7.8]]
weight = [[0.5, 1.5, 0.9, 0.5, 0.8],
          [1.5, 1.5, 1.9, 4.5, 0.8],
          [0.25, -1.5, -0.9, 0.5, 7.8]]
bias = [2, 8, 0.9]

output = np.dot(input, np.array(weight).T) + bias
print(output)

[[ 20.62   79.02  -12.975]
 [ 12.02   31.42  -73.825]
 [ 21.7    40.1    51.405]]
