**1. Imports**

In [6]:
import numpy as np
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense, Flatten
from keras.utils import to_categorical
import pandas as pd
import cv2
import os 


**2. Data Visualization**

In [13]:
csv_path_Train = '/Users/lohries/Downloads/Placas/Train.csv'
images_path = '/Users/lohries/Downloads/Placas'
train_images = []
data = pd.read_csv(csv_path_Train)
data.head()

Width  Height  Roi.X1  ...  Roi.Y2  ClassId                            Path
0     27      26       5  ...      20       20  Train/20/00020_00000_00000.png
1     28      27       5  ...      22       20  Train/20/00020_00000_00001.png
2     29      26       6  ...      21       20  Train/20/00020_00000_00002.png
3     28      27       5  ...      22       20  Train/20/00020_00000_00003.png
4     28      26       5  ...      21       20  Train/20/00020_00000_00004.png

[5 rows x 8 columns]

In [14]:
for index, row in data.iterrows():
    images_path = os.path.join(images_path, row["Path"])
    if os.path.exists(images_path) and images_path.endswith(".png"):
        try:
            image = cv2.imread(images_path)
            if image is not None:
                image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
                train_images.append(image)
            else:
                print("Erro na encontra do path")
        except Exception as e:
            print("Erro em processar imagem")

    else:
        print("Imagem nao encontrada")


Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao encontrada
Imagem nao

In [10]:
train_labels = data["ClassId"].values
print(train_labels)


[16  1 38 ...  6  7 10]


array([16,  1, 38, ...,  6,  7, 10])

In [9]:
csv_path_Test = '/Users/lohries/Downloads/Placas/Test.csv'
data = pd.read_csv(csv_path_Test)
test_labels = data["ClassId"].values
print(test_labels)


[16  1 38 ...  6  7 10]
